const mongoose = require('mongoose');
const AppError = require('./../utils/appError');

const errDEV = (err, res) => {
  res.status(err.statusCode).json({
    status: err.status,
    message: err.message,
    error: err,
    stack: err.stack,
  });
};

const errPROD = (err, res) => {
  // operational error: trusted error (generated by us) -> send to client
  if (err.isOperational) {
    res.status(err.statusCode).json({
      status: err.status,
      message: err.message,
    });
    // Programming error or something unknow : hide from client
  } else {
    console.error(err);

    res.status(500).json({
      status: 'error',
      message: 'Something went wrong',
    });
  }
};

const handleMongooseCastError = (err) =>
  new AppError(`Invalid ${err.path}: ${err.value}`, 400);

const handleMongoDuplicateError = (err) =>
  new AppError(
    `Duplicate field value: ${err.keyValue.name}, Please use another value`,
    400,
  );

const handleMongooseValidationError = (err) => {
  const messages = Object.values(err.errors).map((el) => el.message);
  return new AppError(`Invalid input data. ${messages.join('. ')}`, 400);
};

module.exports = (err, req, res, next) => {
  err.statusCode = err.statusCode || 500;
  err.status = err.status || 'failed';

  if (process.env.NODE_ENV === 'development') {
    errDEV(err, res);
  } else if (process.env.NODE_ENV === 'production') {
    let error;
    if (err instanceof mongoose.Error.CastError) {
      error = handleMongooseCastError(err);
    }
    if (err.code === 11000) {
      error = handleMongoDuplicateError(err);
    }
    if (err instanceof mongoose.Error.ValidationError) {
      error = handleMongooseValidationError(err);
    }

    errPROD(error, res);
  }
};
