const mongoose = require('mongoose');
// eslint-disable-next-line import/no-extraneous-dependencies
const JWT = require('jsonwebtoken');
const AppError = require('./../utils/appError');

const errDEV = (err, req, res) => {
  if (req.originalUrl.startsWith('/api')) {
    return res.status(err.statusCode).json({
      status: err.status,
      error: err,
      message: err.message,
      stack: err.stack,
    });
  }

  // B) RENDERED WEBSITE
  console.error('ERROR 💥', err);
  return res.status(err.statusCode).render('error', {
    title: 'Something went wrong!',
    msg: err.message,
  });
};

const errPROD = (err, req, res) => {
  // A) API
  if (req.originalUrl.startsWith('/api')) {
    // A) Operational, trusted error(genereated by us devs): send message to client
    if (err.isOperational) {
      return res.status(err.statusCode).json({
        status: err.status,
        message: err.message,
      });
    }
    // B) Programming or other unknown error: don't leak error details to client
    // 1) Log error
    console.error('ERROR 💥', err);
    // 2) Send generic message
    return res.status(500).json({
      status: 'error',
      message: 'Something went very wrong!',
    });
  }

  // B) RENDERED WEBSITE
  // A) Operational, trusted error (generated by us devs): send message to client
  if (err.isOperational) {
    console.log(err);
    return res.status(err.statusCode).render('error', {
      title: 'Something went wrong!',
      msg: err.message,
    });
  }
  // B) Programming or other unknown error: don't leak error details to client
  // 1) Log error
  console.error('ERROR 💥', err);
  // 2) Send generic message
  return res.status(err.statusCode).render('error', {
    title: 'Something went wrong!',
    msg: 'Please try again later.',
  });
};

const handleMongooseCastError = (err) =>
  new AppError(`Invalid ${err.path}: ${err.value}`, 400);

const handleMongoDuplicateError = (err) =>
  new AppError(
    `Duplicate field value: ${err.keyValue.name}, Please use another value`,
    400,
  );

const handleMongooseValidationError = (err) => {
  const messages = Object.values(err.errors).map((el) => el.message);
  return new AppError(`Invalid input data. ${messages.join('. ')}`, 400);
};

const handleJwtWebTokenError = (err) =>
  new AppError('Invalid JWT token, cannot verify user. Please try again!', 401);

const handleJwtExpiredError = (err) =>
  new AppError('Your token has expired!, kindy login again', 401);

module.exports = (err, req, res, next) => {
  err.statusCode = err.statusCode || 500;
  err.status = err.status || 'failed';

  if (process.env.NODE_ENV === 'development') {
    errDEV(err, req, res);
  } else if (process.env.NODE_ENV === 'production') {
    let error = err;
    if (err instanceof mongoose.Error.CastError)
      error = handleMongooseCastError(err);

    if (err.code === 11000) error = handleMongoDuplicateError(err);

    if (err instanceof mongoose.Error.ValidationError)
      error = handleMongooseValidationError(err);

    if (err instanceof JWT.JsonWebTokenError) err = handleJwtWebTokenError(err);

    if (err instanceof JWT.TokenExpiredError) err = handleJwtExpiredError(err);

    errPROD(error, req, res);
  }
};
